src/Entity/Rdv.php
<?php

namespace App\Entity;

use App\Repository\RdvRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RdvRepository::class)]
class Rdv
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $NumRdv = null;

    #[ORM\Column]
    private ?int $date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumRdv(): ?int
    {
        return $this->NumRdv;
    }

    public function setNumRdv(int $NumRdv): static
    {
        $this->NumRdv = $NumRdv;

        return $this;
    }

    public function getDate(): ?int
    {
        return $this->date;
    }

    public function setDate(int $date): static
    {
        $this->date = $date;

        return $this;
    }
}

src/Form/RdvType.php
<?php

namespace App\Form;

use App\Entity\Rdv;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RdvType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('NumRdv')
            ->add('date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Rdv::class,
        ]);
    }
}

src/Controller/RdvController.php
<?php

namespace App\Controller;

use App\Entity\Rdv;
use App\Form\RdvType;
use App\Repository\RdvRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

class RdvController extends AbstractController
{
    #[Route('/rdvs', name: 'rdv_index', methods: ['GET'])]
    public function index(RdvRepository $rdvRepository): Response
    {
        $rdvs = $rdvRepository->findAll();

        return $this->render('rdv/index.html.twig', [
            'rdvs' => $rdvs,
        ]);
    }

    #[Route('/rdv/new', name: 'rdv_new')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $rdv = new Rdv();

        $form = $this->createForm(RdvType::class, $rdv);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($rdv);
            $entityManager->flush();

            return $this->redirectToRoute('rdv_index');
        }

        return $this->render('rdv/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/rdv/{id}', name: 'rdv_show', methods: ['GET'])]
    public function show(RdvRepository $rdvRepository, int $id): Response
    {
        $rdv = $rdvRepository->find($id);

        if (!$rdv) {
            throw $this->createNotFoundException('RDV not found');
        }

        return $this->render('rdv/show.html.twig', [
            'rdv' => $rdv,
        ]);
    }

    #[Route('/rdv/{id}/edit', name: 'rdv_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, EntityManagerInterface $entityManager, RdvRepository $rdvRepository, int $id): Response
    {
        $rdv = $rdvRepository->find($id);

        if (!$rdv) {
            throw $this->createNotFoundException('RDV not found');
        }

        $form = $this->createForm(RdvType::class, $rdv);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('rdv_index');
        }

        return $this->render('rdv/edit.html.twig', [
            'rdv' => $rdv,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/rdv/{id}', name: 'rdv_delete', methods: ['POST'])]
    public function delete(Request $request, EntityManagerInterface $entityManager, RdvRepository $rdvRepository, int $id): Response
    {
        $rdv = $rdvRepository->find($id);

        if (!$rdv) {
            throw $this->createNotFoundException('RDV not found');
        }

        if ($this->isCsrfTokenValid('delete'.$rdv->getId(), $request->request->get('_token'))) {
            $entityManager->remove($rdv);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rdv_index');
    }
}

templates/rdv/edit.html.twig
{# templates/rdv/edit.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Edit RDV{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>Edit RDV</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary mt-3">Update RDV</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/rdv/index.html.twig
{# templates/rdv/index.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}List of RDVs{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="mt-4">List of RDVs</h1>
        <a  href="{{ path('rdv_new') }}" class="btn btn-success my-4">Add New RDV</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">RDV Number</th>
                    <th scope="col">Date</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for rdv in rdvs %}
                    <tr>
                        <td>{{ rdv.id }}</td>
                        <td>{{ rdv.numRdv }}</td>
                        <td>{{ rdv.date }}</td>
                        <td>
                            <a href="{{ path('rdv_show', {'id': rdv.id}) }}" class="btn btn-primary btn-sm">Show</a>
                            <a href="{{ path('rdv_edit', {'id': rdv.id}) }}" class="btn btn-warning btn-sm">Edit</a>
                            <form action="{{ path('rdv_delete', {'id': rdv.id}) }}" method="post" class="d-inline">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rdv.id) }}">
                                <button type="submit" class="btn btn-danger btn-sm" >Delete</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/rdv/new.html.twig
{# templates/rdv/new.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}New RDV{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>New RDV</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary mt-3">Create RDV</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/rdv/show.html.twig
{# templates/rdv/show.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}RDV Details{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>RDV Details</h1>
        <p><strong>RDV Number:</strong> {{ rdv.numRdv }}</p>
        <p><strong>Date:</strong> {{ rdv.date }}</p>
        <a href="{{ path('rdv_index') }}" class="btn btn-primary">Back to RDVs</a>
    </div>
{% endblock %}